# Generated by Django 5.2.1 on 2025-05-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("assigned", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("serial", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("depreciation", models.CharField(max_length=100)),
                ("image", models.URLField(max_length=500)),
            ],
        ),
    ]
